hub:
  world: 'world'
  x: 0
  y: 100
  z: 0
  yaw: 0
  pitch: 0
  mountain_x: 0
  mountain_y: 100
  mountain_z: 0
  mountain_yaw: 0
  mountain_pitch: 0
dhub:
  world: 'dhub'
  x: 0
  y: 100
  z: 0
  yaw: 0
  pitch: 0
database:
  user: "skyblock"
  name: "minecraft"
  password: "P@ssword"
  host: 127.0.0.1
  port: 3306
use-sqlite: true
islands:
  x: 7.0
  y: 100
  z: 7.0
#-------------------------------------------------
#                 Wardrobe Config                -
#-------------------------------------------------

Admin-Permission: Wardrobe.Admin

Title: "Wardrobe"
#------------Slot-Permission--------------
Slot-Permission:
  Slot-1:
    Permission: group.default
    Require-Prefix: "&7DEFAULT"
  Slot-2:
    Permission: group.default
    Require-Prefix: "&7DEFAULT"
  Slot-3:
    Permission: group.vip
    Require-Prefix: "&aVIP"
  Slot-4:
    Permission: group.vip
    Require-Prefix: "&aVIP"
  Slot-5:
    Permission: group.vip
    Require-Prefix: "&aVIP"
  Slot-6:
    Permission: group.vip+
    Require-Prefix: "&aVIP&6+"
  Slot-7:
    Permission: group.vip+
    Require-Prefix: "&aVIP&6+"
  Slot-8:
    Permission: group.vip+
    Require-Prefix: "&aVIP&6+"
  Slot-9:
    Permission: group.vip+
    Require-Prefix: "&aVIP&6+"
  Slot-10:
    Permission: group.mvp
    Require-Prefix: "&bMVP"
  Slot-11:
    Permission: group.mvp
    Require-Prefix: "&bMVP"
  Slot-12:
    Permission: group.mvp
    Require-Prefix: "&bMVP"
  Slot-13:
    Permission: group.mvp
    Require-Prefix: "&bMVP"
  Slot-14:
    Permission: group.mvp+
    Require-Prefix: "&bMVP&c+"
  Slot-15:
    Permission: group.mvp+
    Require-Prefix: "&bMVP&c+"
  Slot-16:
    Permission: group.mvp+
    Require-Prefix: "&bMVP&c+"
  Slot-17:
    Permission: group.mvp+
    Require-Prefix: "&bMVP&c+"
  Slot-18:
    Permission: group.mvp+
    Require-Prefix: "&bMVP&c+"
#-----------Items-in-GUI-------------------------
Locked-Slot:
  Helmet-Slot:
    Name: "&7Slot %Slot%: &cLocked"
    Lore:
      - "&7This wardrobe slot is locked and"
      - "&7cannot be used."
      - ""
      - "&cRequires %Permission_Require_Prefix%"
  Chestplate-Slot:
    Name: "&7Slot %Slot%: &cLocked"
    Lore:
      - "&7This wardrobe slot is locked and"
      - "&7cannot be used."
      - ""
      - "&cRequires %Permission_Require_Prefix%"
  Leggings-Slot:
    Name: "&7Slot %Slot%: &cLocked"
    Lore:
      - "&7This wardrobe slot is locked and"
      - "&7cannot be used."
      - ""
      - "&cRequires %Permission_Require_Prefix%"
  Boots-Slot:
    Name: "&7Slot %Slot%: &cLocked"
    Lore:
      - "&7This wardrobe slot is locked and"
      - "&7cannot be used."
      - ""
      - "&cRequires %Permission_Require_Prefix%"
  Locked-Button:
    Name: "&7Slot %Slot%: &cLocked"
    Lore:
      - "&7This wardrobe slot is locked and"
      - "&7cannot be used."
      - ""
      - "&cRequires %Permission_Require_Prefix%"
Availabel-Slot:
  Helmet-Slot:
    Name: "&aSlot %Slot% Helmet"
    Lore:
      - "&7Place a helmet here to add it"
      - "&7to the armor set."
  Chestplate-Slot:
    Name: "&aSlot %Slot% Chestplate"
    Lore:
      - "&7Place a chestplate here to add"
      - "&7it to the armor set."
  Leggings-Slot:
    Name: "&aSlot %Slot% Leggings"
    Lore:
      - "&7Place a pair of leggings here"
      - "&7to add them to the armor"
  Boots-Slot:
    Name: "&aSlot %Slot% Boots"
    Lore:
      - "&7Place a pair of boots here to"
      - "&7add them to the armor set."
  Empty-Slot-Button:
    Name: "&7Slot %Slot%: &cEmpty"
    Lore:
      - "&7This wardrobe slot contains no"
      - "&7armor."
  Ready-Button:
    Name: "&7Slot %Slot%: &aReady"
    Lore:
      - "&7This wardrobe slot is ready to"
      - "&7be equipped."
      - ""
      - "&eClick to equip this armor set!"
  Equipped-Button:
    Name: "&7Slot %Slot%: &aEquipped"
    Lore:
      - "&7This wardrobe slot contains your"
      - "&7current armor set."
      - ""
      - "&eClick to unequip this armor set!"
#------------Button--------------
Go-Back-Button:
  Enable: true
  Command: sbmenu
  Slot: 48
  Name: "&aGo Back"
  Lore: ""
Close-Button:
  Enable: true
  Slot: 49
  Name: "&cClose"
  Lore: ""
Next-Page-Button:
  Enable: true
  Slot: 53
  Name: "&aNext Page"
  Lore:
    - "&ePage 2"
Previous-Page-Button:
  Enable: true
  Slot: 45
  Name: "&aPrevious Page"
  Lore:
    - "&ePage 1"
#--------------Item-Check---------------------------
Allow-Item:
  # set none to skip this check
  # it will allow that item if it has all of this check
  Helmet-Slot:
    # default allow items: all kind of helmet
    Name: none
    # if one of the lore line of an item contains this String it will allow to put that in the gui
    Lore: none
    Type:
      - "PLAYER_HEAD"
      - "GLASS"
    # if an item has that check it will allow it to put in to the gui no matter if it not contains the top check
    Specific-Check-Lore: "HELMET"
  Chestplate-Slot:
    # default allow items: all kind of chestplate, elytra
    Name: none
    # if one of the lore line of an item contains this String it will allow to put that in the gui
    Lore: none
    Type: none
    # if an item has that check it will allow it to put in to the gui no matter if it not contains the top check
    Specific-Check-Lore: "CHESTPLATE"
  Leggings-Slot:
    # default allow items: all kind of leggings
    Name: none
    # if one of the lore line of an item contains this String it will allow to put that in the gui
    Lore: none
    Type: none
    # if an item has that check it will allow it to put in to the gui no matter if it not contains the top check
    Specific-Check-Lore: "LEGGINGS"
  Boots-Slot:
    # default allow items: all kind of boots
    Name: none
    # if one of the lore line of an item contains this String it will allow to put that in the gui
    Lore: none
    Type: none
    # if an item has that check it will allow it to put in to the gui no matter if it not contains the top check
    Specific-Check-Lore: "BOOTS"
#------------------------Message------------------------
Wardrobe_Message:
  # Please just use normal message
  Permission_Denied: '&fUnknown command. Type "/help" for help.'
  No_Space: "&cYou don't have enough space in your inventory!"
  Modify_Armor_Denied: "&cYou can not modify your equipped armor set!"
