name: HypixelSkyblockCore 
version: ${project.version}
main: me.godspunky.skyblock.Skyblock
authors: [ Norysight, Dumbo, Hamza, Epic portal, Furyloxx ]
description: A core for Hypixel skyblock
commands:
  setrank:
  wardrobe:
