name: GodSpunkySkyblockCore
version: ${project.version}
main: me.adarsh.godspunkycore.Skyblock
authors: [ Adarsh, Epicportal, Devil, Legit]
description: A core for godspunky skyblock
commands:
  setrank:
  wardrobe: