name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Install Spigot Build tools (1.8.8)
      uses: SpraxDev/Action-SpigotMC@v4
      with:
        versions: 1.8.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)"

    - name: Add Jar to GitHub releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.REPO_TOKEN }}"
        automatic_release_tag: "${{ steps.tag.outputs.release_tag }}"
        prerelease: false
        title: "Release ${{ steps.tag.outputs.release_tag }}"
        files: |
          target/*.jar
